---
version: 2
updates:
  - package-ecosystem: github-actions
    # Workflow files stored in the default location of `.github/workflows`
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "cyclimse"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "cyclimse"
