---
name: Set up poetry

description: Install poetry and python dependencies

inputs:
  groups:
    description: "Poetry dependencies groups."
    required: true
  python-version:
    description: "Python version."
    required: true

runs:
  using: "composite"
  steps:
    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ inputs.python-version }}-v1

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
      if: steps.cached-poetry.outputs.cache-hit != 'true'

    - name: Cache Poetry dependencies
      id: cache-poetry-deps
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry dependencies
      shell: bash
      run: poetry install --no-interaction --no-root --only ${{ inputs.groups }}
      if: steps.cache-deps.outputs.cache-hit != 'true'
