name: Pytest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ubuntu-22.04
    container: python:${{ matrix.python-version }}-alpine
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-poetry
        with:
          groups: "dev"
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        working-directory: tests
        run: poetry run pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
